### ISSUE TITLE
Cannot find PRNU functions - Weiner_adaptive

### ISSUE THREAD

**Issue by StephenAH** [polimi-ispl/prnu-anonymization-detector#2]
Hi, 

When running db_classes.py, get error message when looking for PRNU functions

from prnu.prnu.functions import wiener_adaptive, zero_mean_total

Is this missing from the build?

**Comment by nicobonne** [comment]
Hi @StephenAH , 
sorry for the late reply, I somehow missed the notification.

PRNU functions are contained into the submodule [prnu](https://github.com/polimi-ispl/prnu-python/tree/ebf0ec76e1aea8683d76707011ee16b29eb0619a). As mentioned [here](https://stackoverflow.com/a/4438292/3409864), in order to clone the repository with the submodule you need to add the `--recurse-submodules` flag to the `clone` command, for instance:
`git clone --recurse-submodules https://github.com/polimi-ispl/prnu-anonymization-detector.git`

Alternatively, you can clone the [prnu](https://github.com/polimi-ispl/prnu-python/tree/ebf0ec76e1aea8683d76707011ee16b29eb0619a) repository into your already cloned `prnu` folder (which I desume is empty).

Let me know if this solve the issue, I'm going to add this information to the README.

**Comment by StephenAH** [comment]
Thanks Nicolo,

Appreciate your response.  Will test and revert.  However, will be in a week now as I am out of the office.

Regards
Stephen Holmes
CTO & Head of Security Systems
ObjectTech Group Ltd
+44 207 993 5512
[signature_304301741]
The company accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.
